### ISSUE TITLE
generator carter:migration not found

### ISSUE THREAD

**Issue by TyrelDenison** [gillies-dunlop/carter#6]
I cannot run the migration generator. It returns a generator not found message. How should I run the migrations?

**Comment by jankeesvw** [comment]
I have the same issue..

```
/Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- state_machine (LoadError)
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/carter-0.7.2/lib/carter/state_machine.rb:1:in `<top (required)>'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/carter-0.7.2/lib/carter.rb:6:in `<top (required)>'
    from /Users/jankeesvw/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /Users/jankeesvw/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
    from /Users/jankeesvw/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /Users/jankeesvw/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
    from /Users/jankeesvw/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /Users/jankeesvw/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
    from /Users/jankeesvw/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /Users/jankeesvw/Documents/code/ArsType/config/application.rb:7:in `<top (required)>'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:82:in `require'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:82:in `preload'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:140:in `serve'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

**Comment by pailoro** [comment]
Same problem here:

fernando@Apolo:~/Dropbox/Code/XSTreams/xtreamsapp$ rails generate carter:migration
/var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- state_machine (LoadError)
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`block in require'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`require'
    from /var/lib/gems/1.9.1/gems/carter-0.7.2/lib/carter/state_machine.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in`require'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /var/lib/gems/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
    from /var/lib/gems/1.9.1/gems/carter-0.7.2/lib/carter.rb:6:in`<top (required)>'
    from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `require'
    from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in`block (2 levels) in require'
    from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in `each'
    from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:70:in`block in require'
    from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in `each'
    from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:59:in`require'
    from /usr/lib/ruby/vendor_ruby/bundler.rb:132:in `require'
    from /home/fernando/Dropbox/Code/XSTreams/xtreamsapp/config/application.rb:7:in`<top (required)>'
    from /var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/commands.rb:24:in `require'
    from /var/lib/gems/1.9.1/gems/railties-3.2.17/lib/rails/commands.rb:24:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by retailify** [comment]
Add following to your Gemfile:
gem 'state_machine', '~> 1.2.0'
and run bundle install

**Comment by TyrelDenison** [comment]
I've had to move on long ago. I'm closing the issue for now on the assumption that the instructions from retailify fix the issue. If that's not the case, please open an new issue or, if possible, reopen this one.
